import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const theme = process.env.THEME ?? "light";
await page.goto("http://localhost:5173/", { waitUntil: "networkidle" });
await page.evaluate((t) => localStorage.setItem("theme", t), theme);
await page.goto("http://localhost:5173/p/default/c/blogs", { waitUntil: "networkidle" });
await page.waitForTimeout(900);
await page.locator("a").filter({ hasText: "Datalog" }).first().click();
await page.waitForTimeout(2200);
const box = await page.locator("tiptap-editor").boundingBox();
await page.screenshot({ path: `/tmp/editor-${theme}.png`, clip: { x: box.x - 20, y: box.y - 40, width: box.width + 40, height: 320 } });
console.log(`/tmp/editor-${theme}.png`);
await browser.close();
